import Head from "next/head";
import { AdviceCard } from "@/components/AdviceCard/AdviceCard";

import styles from "@/styles/Home.module.scss";

export default function Home() {
  return (
    <>
      <Head>
        <title>Advice generator</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        <link rel="icon" href="/favicon-32x32.png" />
      </Head>
      <main className={styles.container}>
        <AdviceCard />
      </main>
    </>
  );
}
