import Head from "next/head";
import { Manrope } from "@next/font/google";
import { AdviceCard } from "@/components/AdviceCard/AdviceCard";

import styles from "@/styles/Home.module.scss";

const manrope = Manrope({ weight: "800", subsets: [] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Advice generator</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon-32x32.png" />
      </Head>
      <main className={`${manrope.className} ${styles.container}`}>
        <AdviceCard />
      </main>
    </>
  );
}
